apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"log-reader"},"rules":[{"apiGroups":[""],"resources":["namespaces"],"verbs":["get","watch","list"]},{"apiGroups":["apps"],"resources":["deployments"],"verbs":["get","watch","list"]}]}
  creationTimestamp: "2024-07-23T12:39:15Z"
  name: log-reader
  resourceVersion: "23102"
  uid: c932362b-7844-4032-a1e2-2cbaef0b97c0
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
