apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"my-service-account-binding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"log-reader"},"subjects":[{"kind":"ServiceAccount","name":"api-explorer","namespace":"default"}]}
  creationTimestamp: "2024-07-22T13:00:30Z"
  name: my-service-account-binding
  resourceVersion: "8346"
  uid: cca640b9-d1ea-4458-adc4-43cb18b3a821
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log-reader
subjects:
- kind: ServiceAccount
  name: api-explorer
  namespace: default
